#!/usr/bin/env zsh
#!/bin/zsh
MESSAGE=$1
if [ -z "$MESSAGE" ];then MESSAGE="$HOST `date`";fi;

#find ./  -name "._*" -print0 | xargs -0 git rm > /dev/null 2>&1
#find ./  -name "._*" -print0 | xargs -0 rm > /dev/null 2>&1
#find ./  -name "*.swp" -print0 | xargs -0 git rm > /dev/null 2>&1
#find ./  -name "*.swp" -print0 | xargs -0 rm rm > /dev/null 2>&1

echo "git add *"
git add *
echo "git add ."
git add .

echo "git commit -m $MESSAGE"
git commit -m "$MESSAGE"

git push --all google

exit 0
