#!/usr/bin/env zsh
#!/bin/zsh
MESSAGE=$1
if [ -z "$MESSAGE" ];then MESSAGE="$HOST `date`";fi;

find ./  -name "._*" -print0 | xargs -0 git rm 2>&1 /dev/null
find ./  -name "._*" -print0 | xargs -0 rm rm 2>&1 /dev/null
find ./  -name "*.swp" -print0 | xargs -0 git rm rm 2>&1 /dev/null
find ./  -name "*.swp" -print0 | xargs -0 rm rm 2>&1 /dev/null

echo "git add *"
git add *
echo "git add ."
git add .

echo "git commit -m $MESSAGE"
git commit -m "$MESSAGE"

git push -u origin master
exit 0
